name: Security Checks

on:
  push:
    branches:
      - master

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run Snyk to check for vulnerabilities in dependencies
        id: snyk
        uses: snyk/actions/node@master
        with:
          command: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      # - name: Run static code analysis (CodeQL)
      #   uses: github/codeql-action/analyze@v1
      #   with:
      #     languages: javascript
      #     query: "security-and-quality.qls"
      #   continue-on-error: true

      # - name: Upload CodeQL results
      #   uses: github/codeql-action/upload-sarif@v1
      #   with:
      #     sarif_file: ${{github.workspace}}/codeql-results.sarif

      - name: Generate Snyk vulnerability report
        run: snyk test --all-projects --json > snyk-report.json

      - name: Display Snyk vulnerability report
        run: cat snyk-report.json

      - name: Set exit status
        if: always()
        run: echo "Snyk found vulnerabilities."

      # - name: Trivy scanner
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     scan-type: 'fs'
      #     ignore-unfixed: true
      #     hide-progress: true
      #     output: trivy.txt
      #     exit-code: '1'

      # - name: Publish Trivy Output to Summary
      #   if: always()
      #   run: |
      #     if [[ -s trivy.txt ]]; then
      #       {
      #         echo "### Trivy Output"
      #         echo "<details><summary>Click to expand</summary>"
      #         echo ""
      #         echo '```Report'
      #         cat trivy.txt
      #         echo '```'
      #         echo "</details>"
      #       } >> $GITHUB_STEP_SUMMARY
      #     fi