name: NodeJS CI/CD with Snyk

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  opensource-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Snyk CLI to HTML
        run: npm install snyk-to-html -g
      - name: Run Snyk to check for vulnerabilities in dependencies
        uses: snyk/actions/node@master
        with:
          command: test --json | snyk-to-html -o results-opensource.html
        # continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  code-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check for vulnerabilities in code
        uses: snyk/actions/node@master
        with:
          command: code test --json | snyk-to-html -o results-code.html
        # continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  handle-pr:
    needs: [opensource-security, code-security]
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Accept or Decline PR based on Snyk Results
        if: ${{ ! needs.opensource-security.result == failure() && ! needs.code-security.result == failure() }}
        run: 
          echo "No vulnerabilities found, PR can be merged."
          
      - name: PR post decline step
        if: ${{ failure() }}
        run: 
          echo "Vulnerabilities found, declining PR."
          exit 1 

  # summary-report:
  #   needs: [opensource-security, code-security]
  #   runs-on: ubuntu-latest
  #   if: always()
  #   steps:
  #     - uses: actions/checkout@v2    
  #     - name: Add Job Summary from Snyk reports
  #       uses: medly/snyk-job-summary-action@v1.0.0
  #       with:
  #           dependencies-report-path: snyk_dependencies.json 
  #           code-report-path: snyk_code.json