name: NodeJS CI/CD with Snyk

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  opensource-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Run Snyk to check for vulnerabilities in dependencies
        uses: snyk/actions/node@master
        with:
          command: test
          scan-type: 'fs'
          ignore-unfixed: true
          output: snyk.txt
          exit-code: '1'
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

  code-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check for vulnerabilities in code
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test

  release:
    needs: [opensource-security, code-security]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set Git user
        run: |
          git config user.email "mrdavidsaguev@proton.me"
          git config user.name "dave"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  opensource-monitor:
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor

  opensource-report:
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - name: Publish Snyk Open Source Output to Summary
        if: always()
        run: |
          if [[ -s snyk.txt ]]; then
            {
              echo "### Trivy Output"
              echo "<details><summary>Click to expand</summary>"
              echo ""
              echo '```Report'
              cat snyk.txt
              echo '```'
              echo "</details>"
            } >> $GITHUB_STEP_SUMMARY
          fi


# name: Security Checks

# on:
#   push:
#     branches:
#       - master

# jobs:
#   security:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Run Snyk to check for vulnerabilities in dependencies
#         id: snyk
#         uses: snyk/actions/node@master
#         with:
#           command: test
#         env:
#           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
#         continue-on-error: true
