name: NodeJS CI/CD with Snyk

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  opensource-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check for vulnerabilities in dependencies
        uses: snyk/actions/node@master
        with:
          command: test --all-projects --json-file-output=snyk_dependencies.json
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  code-security:
    runs-on: ubuntu-latest
    outputs:
      code-ok: ${{ steps.snyk-code-output.outputs.is-secure }}
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check for vulnerabilities in code
        id: snyk-code
        uses: snyk/actions/node@master
        with:
          command: code test --all-projects --json-file-output=snyk_code.json
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  handle-pr:
    needs: [opensource-security, code-security]
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Accept or Decline PR based on Snyk Results
        run: |
          if [!contains(needs.*.result, 'failure')]; then
            echo "No vulnerabilities found, PR can be merged."
          else
            echo "Vulnerabilities found, declining PR."
            exit 1  # This will fail the workflow if vulnerabilities are found

  summary-report:
    needs: [opensource-security, code-security]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2    
      - name: Add Job Summary from Snyk reports
        uses: medly/snyk-job-summary-action@v1.0.0
        with:
            dependencies-report-path: snyk_dependencies.json 
            code-report-path: snyk_code.json 
        if: always()
